// This file is auto generated do not edit
const std = @import("std");
pub const c = @import("gdk/c.zig");
pub usingnamespace @import("gdk/enums.zig");
pub usingnamespace @import("gdk/flags.zig");
pub usingnamespace @import("gdk/constants.zig");

pub const AppLaunchContext = @import("gdk/app_launch_context.zig").AppLaunchContext;
pub const ButtonEvent = @import("gdk/button_event.zig").ButtonEvent;
pub const CairoContext = @import("gdk/cairo_context.zig").CairoContext;
pub const Clipboard = @import("gdk/clipboard.zig").Clipboard;
pub const ContentDeserializer = @import("gdk/content_deserializer.zig").ContentDeserializer;
pub const ContentFormats = @import("gdk/content_formats.zig").ContentFormats;
pub const ContentFormatsBuilder = @import("gdk/content_formats_builder.zig").ContentFormatsBuilder;
pub const ContentProvider = @import("gdk/content_provider.zig").ContentProvider;
pub const ContentProviderClass = @import("gdk/content_provider_class.zig").ContentProviderClass;
pub const ContentSerializer = @import("gdk/content_serializer.zig").ContentSerializer;
pub const CrossingEvent = @import("gdk/crossing_event.zig").CrossingEvent;
pub const Cursor = @import("gdk/cursor.zig").Cursor;
pub const DNDEvent = @import("gdk/dnd_event.zig").DNDEvent;
pub const DeleteEvent = @import("gdk/delete_event.zig").DeleteEvent;
pub const Device = @import("gdk/device.zig").Device;
pub const DevicePad = @import("gdk/device_pad.zig").DevicePad;
pub const DevicePadInterface = @import("gdk/device_pad_interface.zig").DevicePadInterface;
pub const DeviceTool = @import("gdk/device_tool.zig").DeviceTool;
pub const Display = @import("gdk/display.zig").Display;
pub const DisplayManager = @import("gdk/display_manager.zig").DisplayManager;
pub const Drag = @import("gdk/drag.zig").Drag;
pub const DragSurface = @import("gdk/drag_surface.zig").DragSurface;
pub const DragSurfaceInterface = @import("gdk/drag_surface_interface.zig").DragSurfaceInterface;
pub const DragSurfaceSize = @import("gdk/drag_surface_size.zig").DragSurfaceSize;
pub const DrawContext = @import("gdk/draw_context.zig").DrawContext;
pub const Drop = @import("gdk/drop.zig").Drop;
pub const Event = @import("gdk/event.zig").Event;
pub const EventSequence = @import("gdk/event_sequence.zig").EventSequence;
pub const FileList = @import("gdk/file_list.zig").FileList;
pub const FocusEvent = @import("gdk/focus_event.zig").FocusEvent;
pub const FrameClock = @import("gdk/frame_clock.zig").FrameClock;
pub const FrameClockClass = @import("gdk/frame_clock_class.zig").FrameClockClass;
pub const FrameClockPrivate = @import("gdk/frame_clock_private.zig").FrameClockPrivate;
pub const FrameTimings = @import("gdk/frame_timings.zig").FrameTimings;
pub const GLContext = @import("gdk/gl_context.zig").GLContext;
pub const GLTexture = @import("gdk/gl_texture.zig").GLTexture;
pub const GLTextureBuilder = @import("gdk/gl_texture_builder.zig").GLTextureBuilder;
pub const GLTextureBuilderClass = @import("gdk/gl_texture_builder_class.zig").GLTextureBuilderClass;
pub const GLTextureClass = @import("gdk/gl_texture_class.zig").GLTextureClass;
pub const GrabBrokenEvent = @import("gdk/grab_broken_event.zig").GrabBrokenEvent;
pub const KeyEvent = @import("gdk/key_event.zig").KeyEvent;
pub const KeymapKey = @import("gdk/keymap_key.zig").KeymapKey;
pub const MemoryTexture = @import("gdk/memory_texture.zig").MemoryTexture;
pub const MemoryTextureClass = @import("gdk/memory_texture_class.zig").MemoryTextureClass;
pub const Monitor = @import("gdk/monitor.zig").Monitor;
pub const MonitorClass = @import("gdk/monitor_class.zig").MonitorClass;
pub const MotionEvent = @import("gdk/motion_event.zig").MotionEvent;
pub const PadEvent = @import("gdk/pad_event.zig").PadEvent;
pub const Paintable = @import("gdk/paintable.zig").Paintable;
pub const PaintableInterface = @import("gdk/paintable_interface.zig").PaintableInterface;
pub const Popup = @import("gdk/popup.zig").Popup;
pub const PopupInterface = @import("gdk/popup_interface.zig").PopupInterface;
pub const PopupLayout = @import("gdk/popup_layout.zig").PopupLayout;
pub const ProximityEvent = @import("gdk/proximity_event.zig").ProximityEvent;
pub const RGBA = @import("gdk/rgba.zig").RGBA;
pub const Rectangle = @import("gdk/rectangle.zig").Rectangle;
pub const ScrollEvent = @import("gdk/scroll_event.zig").ScrollEvent;
pub const Seat = @import("gdk/seat.zig").Seat;
pub const Snapshot = @import("gdk/snapshot.zig").Snapshot;
pub const SnapshotClass = @import("gdk/snapshot_class.zig").SnapshotClass;
pub const Surface = @import("gdk/surface.zig").Surface;
pub const SurfaceClass = @import("gdk/surface_class.zig").SurfaceClass;
pub const Texture = @import("gdk/texture.zig").Texture;
pub const TextureClass = @import("gdk/texture_class.zig").TextureClass;
pub const TextureDownloader = @import("gdk/texture_downloader.zig").TextureDownloader;
pub const TimeCoord = @import("gdk/time_coord.zig").TimeCoord;
pub const Toplevel = @import("gdk/toplevel.zig").Toplevel;
pub const ToplevelInterface = @import("gdk/toplevel_interface.zig").ToplevelInterface;
pub const ToplevelLayout = @import("gdk/toplevel_layout.zig").ToplevelLayout;
pub const ToplevelSize = @import("gdk/toplevel_size.zig").ToplevelSize;
pub const TouchEvent = @import("gdk/touch_event.zig").TouchEvent;
pub const TouchpadEvent = @import("gdk/touchpad_event.zig").TouchpadEvent;
pub const VulkanContext = @import("gdk/vulkan_context.zig").VulkanContext;

test "gdk" {
    std.testing.refAllDecls(@This());
}