name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo snap install zig --classic --edge
            zig version
            git submodule update --init --recursive
      - name: Test
        run: zig build test
      - name: Test example
        run: |
            cd example
            zig build
